services:
  pg:
    build: .
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=music
    environment:
      POSTGRES_DB: music
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/main
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 3s
      retries: 3
volumes:
  pgdata: